const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#canvas'),ctx=canvas.getContext('2d'),photoInput=$('#photoInput'),logoInput=$('#logoInput');
const state={photo:null,logo:null,mode:'repeat',opacity:.35,size:.22,spacing:.55,pos:{x:1,y:1},dragging:false,dragMoved:false,dragStart:null,quick:false};

const SETTINGS_KEY='stamp-settings';
function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify({mode:state.mode,opacity:state.opacity,size:state.size,spacing:state.spacing,pos:state.pos,format:$('#format').value,quality:$('#quality').value,quick:state.quick}))}
function restoreSettings(){try{const s=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');if(s.mode){state.mode=s.mode;const radio=$('input[name=mode][value="'+s.mode+'"]');if(radio)radio.checked=true}for(const key of ['opacity','size','spacing'])if(Number.isFinite(s[key])){state[key]=s[key];const value=Math.round(s[key]*100);$('#'+key).value=value;$('#'+key+'Value').value=value+'%'}if(s.pos){state.pos=s.pos;$$('.position-grid button').forEach(b=>{const [x,y]=b.dataset.position.split(',').map(Number);b.classList.toggle('active',x===s.pos.x&&y===s.pos.y)})}if(s.format)$('#format').value=s.format;if(s.quality)$('#quality').value=s.quality;state.quick=!!s.quick;$('#quickMode').checked=state.quick;$('#quickModeCard').classList.toggle('active',state.quick);$('#singleOptions').hidden=state.mode!=='single';$('#spacingControl').hidden=state.mode!=='repeat'}catch(e){}}const logoStore={
  open(){return new Promise((resolve,reject)=>{const request=indexedDB.open('stamp-watermark',1);request.onupgradeneeded=()=>request.result.createObjectStore('assets');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})},
  async save(file){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('assets','readwrite');tx.objectStore('assets').put({blob:file,name:file.name,type:file.type,savedAt:Date.now()},'last-logo');tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})},
  async load(){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('assets','readonly'),request=tx.objectStore('assets').get('last-logo');request.onsuccess=()=>{db.close();resolve(request.result)};request.onerror=()=>{db.close();reject(request.error)}})}
};

function fileToImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('לא ניתן לקרוא את הקובץ'))};img.src=url})}
function fitCanvas(img){const max=2600,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale)}
async function loadPhoto(file){if(!file)return;try{state.photo=await fileToImage(file);fitCanvas(state.photo);$('#emptyState').hidden=true;$('#canvasShell').classList.add('ready');$('#downloadButton').disabled=false;$('#canvasHint').textContent=`${state.photo.naturalWidth} × ${state.photo.naturalHeight}`;draw();photoInput.value='';if(state.quick&&state.logo){notify('יוצר ומוריד את התמונה…');setTimeout(exportImage,180)}else $('#editor').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){notify('לא הצלחנו לפתוח את התמונה. נסו JPG או PNG.') }}
async function loadLogo(file,{persist=true}={}){if(!file)return;try{state.logo=await fileToImage(file);$('#logoName').textContent=persist?`${file.name} · נשמר לשימוש הבא`:`${file.name} · נטען מהפעם הקודמת`;$('#logoThumb').innerHTML=`<img alt="תצוגה מקדימה של הלוגו">`;$('#logoThumb img').src=URL.createObjectURL(file);draw();if(persist){await logoStore.save(file);saveSettings();notify('הלוגו נשמר לשימוש הבא')}}catch(e){notify('לא הצלחנו לפתוח או לשמור את הלוגו.') }}
function logoBox(){if(!state.logo)return null;const w=canvas.width*state.size,h=w*(state.logo.naturalHeight/state.logo.naturalWidth),pad=Math.max(16,canvas.width*.025);return{w,h,pad,x:pad+(canvas.width-w-pad*2)*state.pos.x,y:pad+(canvas.height-h-pad*2)*state.pos.y}}
function draw(){if(!state.photo){ctx.clearRect(0,0,canvas.width,canvas.height);return}ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(state.photo,0,0,canvas.width,canvas.height);if(!state.logo)return;ctx.save();ctx.globalAlpha=state.opacity;if(state.mode==='single'){const b=logoBox();ctx.drawImage(state.logo,b.x,b.y,b.w,b.h)}else{const w=canvas.width*state.size,h=w*(state.logo.naturalHeight/state.logo.naturalWidth),gap=Math.max(w*.25,canvas.width*state.spacing*.3),stepX=w+gap,stepY=h+gap*.65;ctx.translate(-stepX*.35,-stepY*.2);ctx.rotate(-Math.PI/12);const extra=canvas.width*.35;for(let y=-extra;y<canvas.height+extra;y+=stepY){const row=Math.round(y/stepY),offset=row%2?stepX/2:0;for(let x=-extra;x<canvas.width+extra;x+=stepX)ctx.drawImage(state.logo,x+offset,y,w,h)}}ctx.restore()}
function notify(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>el.classList.remove('show'),2400)}
photoInput.addEventListener('change',e=>loadPhoto(e.target.files[0]));logoInput.addEventListener('change',e=>loadLogo(e.target.files[0]));
$('#emptyUpload').onclick=()=>photoInput.click();
['dragenter','dragover'].forEach(ev=>$('#photoDrop').addEventListener(ev,e=>{e.preventDefault();e.currentTarget.classList.add('drag')}));
['dragleave','drop'].forEach(ev=>$('#photoDrop').addEventListener(ev,e=>{e.preventDefault();e.currentTarget.classList.remove('drag');if(ev==='drop')loadPhoto(e.dataTransfer.files[0])}));
$$('input[name=mode]').forEach(r=>r.onchange=()=>{state.mode=r.value;$('#singleOptions').hidden=state.mode!=='single';$('#spacingControl').hidden=state.mode!=='repeat';draw();saveSettings()});
[['opacity','opacityValue',v=>state.opacity=v/100],['size','sizeValue',v=>state.size=v/100],['spacing','spacingValue',v=>state.spacing=v/100]].forEach(([id,out,set])=>{$('#'+id).oninput=e=>{set(+e.target.value);$('#'+out).value=e.target.value+'%';draw();saveSettings()}});
$$('.position-grid button').forEach(b=>b.onclick=()=>{const [x,y]=b.dataset.position.split(',').map(Number);state.pos={x,y};$$('.position-grid button').forEach(x=>x.classList.toggle('active',x===b));draw();saveSettings()});
function pointerPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*canvas.width,y:(e.clientY-r.top)/r.height*canvas.height}}
canvas.addEventListener('pointerdown',e=>{state.dragMoved=false;state.dragStart={x:e.clientX,y:e.clientY};if(state.mode!=='single'||!state.logo)return;state.dragging=true;canvas.setPointerCapture(e.pointerId);$('#canvasShell').classList.add('dragging')});
canvas.addEventListener('pointermove',e=>{if(!state.dragging)return;if(state.dragStart&&Math.hypot(e.clientX-state.dragStart.x,e.clientY-state.dragStart.y)>5)state.dragMoved=true;const p=pointerPos(e),b=logoBox();state.pos.x=Math.max(0,Math.min(1,(p.x-b.w/2-b.pad)/(canvas.width-b.w-b.pad*2)));state.pos.y=Math.max(0,Math.min(1,(p.y-b.h/2-b.pad)/(canvas.height-b.h-b.pad*2)));draw();saveSettings()});
canvas.addEventListener('pointerup',()=>{state.dragging=false;$('#canvasShell').classList.remove('dragging')});
canvas.addEventListener('click',()=>{if(state.photo&&!state.dragMoved)photoInput.click()});
function exportImage(){if(!state.photo)return;if(!state.logo){notify('בחרו לוגו לפני ההורדה');logoInput.click();return}const type=$('#format').value,quality=+$('#quality').value,ext=type.split('/')[1].replace('jpeg','jpg');canvas.toBlob(blob=>{if(!blob){notify('השמירה נכשלה');return}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`protected-${Date.now()}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify(state.quick?'התמונה ירדה אוטומטית':'התמונה המוגנת נשמרה')},type,quality)}
$('#downloadButton').onclick=exportImage;
$('#quickMode').onchange=e=>{if(e.target.checked&&!state.logo){e.target.checked=false;notify('בחרו לוגו לפני הפעלת יצירה מהירה');logoInput.click();return}state.quick=e.target.checked;$('#quickModeCard').classList.toggle('active',state.quick);saveSettings();notify(state.quick?'יצירה מהירה הופעלה':'יצירה מהירה כובתה')};
$('#format').onchange=saveSettings;
$('#quality').onchange=saveSettings;
$('#resetButton').onclick=()=>{if(!state.photo&&!state.logo)return;state.photo=null;photoInput.value='';$('#emptyState').hidden=false;$('#canvasShell').classList.remove('ready');$('#downloadButton').disabled=true;$('#canvasHint').textContent='העלו תמונה כדי להתחיל';draw();notify('התמונה אופסה · הלוגו נשמר')};
async function restoreSavedLogo(){try{const saved=await logoStore.load();if(!saved?.blob)return;const file=new File([saved.blob],saved.name||'logo',{type:saved.type||saved.blob.type});await loadLogo(file,{persist:false})}catch(e){}}
restoreSettings();
restoreSavedLogo();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
